config/routes.rb
BpmSales::Engine.routes.draw do
  resources :invoices do
    member do
      put 'mark_paid'
    end
    resources :line_items
  end
  get "report/index"
  get "panel/index"
  resources :customers
  root to: "panel#index"
end

app/models/bpm_sales/customer.rb
module BpmSales
  class Customer < ActiveRecord::Base
  end
end

app/models/bpm_sales/invoice.rb
module BpmSales
  class Invoice < ActiveRecord::Base

    has_many :line_items

    validates_presence_of :bill_to

    #include Payday::Invoiceable

    # Payday won't display invoice numbers unless invoice_number exists on our invoice
    def invoice_number
      id
    end

    def tax_rate
      0.07
    end

    def tax_description
      'GST'
    end

    def shipping_rate
      0
    end

    # Calculates the subtotal of this invoice by adding up all of the line items
    def subtotal
      line_items.inject(BigDecimal.new("0")) { |result, item| result += item.amount }
    end

    # The tax for this invoice, as a BigDecimal
    def tax
      if defined?(tax_rate)
        calculated = subtotal * tax_rate
        return 0 if calculated < 0
        calculated
      else
        0
      end
    end

    # TODO Add a per weight unit shipping cost
    # Calculates the shipping
    def shipping
      if defined?(shipping_rate)
        shipping_rate
      else
        0
      end
    end

    # Calculates the total for this invoice.
    def total
      subtotal + tax + shipping
    end

    def overdue?
      defined?(:due_at) && ((due_at.is_a?(Date) && due_at < Date.today) || (due_at.is_a?(Time) && due_at < Time.now))  && !paid_at
    end

    def paid?
      defined?(:paid_at) && !!paid_at
    end

    # Renders this invoice to pdf as a string
    def render_pdf
      Payday::PdfRenderer.render(self)
    end

    # Renders this invoice to pdf
    def render_pdf_to_file(path)
      Payday::PdfRenderer.render_to_file(self, path)
    end

    # Iterates through the details on this invoiceable. The block given should accept
    # two parameters, the detail name and the actual detail value.
    def each_detail(&block)
      return if defined?(invoice_details).nil?

      invoice_details.each do |detail|
        block.call(detail[0], detail[1])
      end
    end


  end
end

app/models/bpm_sales/line_item.rb
module BpmSales
  class LineItem < ActiveRecord::Base
    include Payday::LineItemable

    belongs_to :invoice

    #attr_accessor :description, :quantity, :display_quantity, :display_price, :price
    attr_accessor :display_quantity, :display_price
    #
    #Initializes a new LineItem
    #def initialize(options={})
    #  self.quantity = options[:quantity] || "1"
    #  self.display_quantity = options[:display_quantity]
    #  self.display_price = options[:display_price]
    #  self.price = options[:price] || "0.00"
    #  self.description = options[:description] || ""
    #end

    # Sets the quantity of this {LineItem}
    #def quantity=(value)
    #  @quantity = BigDecimal.new(value.to_s)
    #end
    #
    ## Sets the price for this {LineItem}
    #def price=(value)
    #  @price = BigDecimal.new(value.to_s)
    #end





    #validates_numericality_of :price
    #validates_numericality_of :quantity
    validates_presence_of :description
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  include Payday::Invoiceable
  
  has_many :line_items
end

app/controllers/bpm_sales/application_controller.rb
class BpmSales::ApplicationController < ApplicationController
end

app/controllers/bpm_sales/customers_controller.rb
require_dependency "bpm_sales/application_controller"

module BpmSales
  class CustomersController < ApplicationController
    before_action :set_customer, only: [:show, :edit, :update, :destroy]

    # GET /customers
    def index
      @customers = Customer.all
    end

    # GET /customers/1
    def show
    end

    # GET /customers/new
    def new
      @customer = Customer.new
    end

    # GET /customers/1/edit
    def edit
    end

    # POST /customers
    def create
      @customer = Customer.new(customer_params)

      if @customer.save
        redirect_to @customer, notice: 'Customer was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /customers/1
    def update
      if @customer.update(customer_params)
        redirect_to @customer, notice: 'Customer was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /customers/1
    def destroy
      @customer.destroy
      redirect_to customers_url, notice: 'Customer was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_customer
        @customer = Customer.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def customer_params
        params.require(:customer).permit(:email, :name, :phone, :company, :remark)
      end
  end
end

app/controllers/bpm_sales/invoices_controller.rb
require_dependency "bpm_sales/application_controller"

module BpmSales
  class InvoicesController < ApplicationController
    before_action :set_invoice, only: [:show, :edit, :update, :destroy, :mark_paid]

    # GET /invoices
    def index
      @invoices = Invoice.all
    end

    # GET /invoices/1
    def show
      respond_to do |format|
        format.html
        format.pdf {
          Payday::Config.default.invoice_logo = "app/assets/images/logo.png"
          Payday::Config.default.company_name = "Asental Pte. Ltd."
          Payday::Config.default.company_details = "Innovation Centre BLK 2, #02-235 18 Nanyang Drive, Singapore 637723 \nsamuel.shen@asental.com"
          send_data(@invoice.render_pdf, :filename => "Invoice #{@invoice.id}.pdf", :type => "application/pdf", :disposition => "inline") }
      end
    end

    # GET /invoices/new
    def new

      @invoice = Invoice.new
      #Payday::Config.default.invoice_logo = "app/assets/images/logo.png"
      #Payday::Config.default.company_name = "Asental Pte. Ltd."
      #Payday::Config.default.company_details = "Innovation Centre BLK 2, #02-235 18 Nanyang Drive, Singapore 637723 \nsamuel.shen@asental.com"
      #invoice = Payday::Invoice.new(:invoice_number => 1, :bill_to => "Another Pte. Ltd.\nclient@another.com")
      #invoice.line_items << LineItem.new(:price => 20, :quantity => 5, :description => "Pants")
      #invoice.line_items << LineItem.new(:price => 10, :quantity => 3, :description => "Shirts")
      #invoice.line_items << LineItem.new(:price => 5, :quantity => 200, :description => "Hats")
      #invoice.render_pdf_to_file("app/assets/invoices/sample.pdf")
    end

    # GET /invoices/1/edit
    def edit
    end

    # POST /invoices
    def create
      @invoice = Invoice.new(invoice_params)

      if @invoice.save
        redirect_to @invoice, notice: 'Invoice was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /invoices/1
    def update
      if @invoice.update(invoice_params)
        redirect_to @invoice, notice: 'Invoice was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /invoices/1
    def destroy
      @invoice.destroy
      redirect_to invoices_url, notice: 'Invoice was successfully destroyed.'
    end

    def mark_paid
      if !@invoice.paid?
        @invoice.update_attribute(:paid_at, Time.now)
      end
      redirect_to @invoice and return
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def invoice_params
      params.require(:invoice).permit(:due_at, :pay_at, :total, :bill_to, :customer_id)
    end
  end
end

app/controllers/bpm_sales/line_items_controller.rb
require_dependency "bpm_sales/application_controller"

module BpmSales
  class LineItemsController < ApplicationController
    before_action :set_line_item, only: [:show, :edit, :update, :destroy]

    # GET /line_items
    def index
      @line_items = LineItem.all
    end

    # GET /line_items/1
    def show
    end

    # GET /line_items/new
    def new
      @invoice = Invoice.find(params[:invoice_id])
      @line_item = LineItem.new
    end

    # GET /line_items/1/edit
    def edit
      @invoice = Invoice.find(params[:invoice_id])
      @line_item = LineItem.find(params[:id])
    end

    # POST /line_items
    def create
      @invoice = Invoice.find(params[:invoice_id])
      @line_item = LineItem.new(line_item_params, invoice_id: params[:invoice_id].to_i)
      if @line_item.save
        redirect_to invoice_url(@invoice), notice: 'Customer was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /line_items/1
    def update
      invoice_url(@invoice)
    end

    # DELETE /line_items/1
    def destroy
      @line_item.destroy
      redirect_to line_items_url, notice: 'LineItem was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def line_item_params
      temp=params.require(:line_item).permit(:price, :quantity, :description)
      temp[:invoice_id]=params[:invoice_id]
      temp
    end
  end
end

app/controllers/bpm_sales/panel_controller.rb
require_dependency "bpm_sales/application_controller"

module BpmSales
  class PanelController < ApplicationController
    def index
      @total_customer_count=Customer.count
      @new_customer_count=Customer.where('created_at > ?', Time.zone.now-1.month).count
      @total_invoice_count=Invoice.count
      @new_invoice_count=Invoice.where('created_at > ?', Time.zone.now-1.day).count
    end
  end
end

app/controllers/bpm_sales/report_controller.rb
require_dependency "bpm_sales/application_controller"

module BpmSales
  class ReportController < ApplicationController
    def index
    end
  end
end

app/helpers/bpm_sales/application_helper.rb
module BpmSales
  module ApplicationHelper
  end
end

app/helpers/bpm_sales/customers_helper.rb
module BpmSales
  module CustomersHelper
  end
end

app/helpers/bpm_sales/invoices_helper.rb
module BpmSales
  module InvoicesHelper
  end
end

app/helpers/bpm_sales/line_items_helper.rb
module BpmSales
  module LineItemsHelper
  end
end

app/helpers/bpm_sales/panel_helper.rb
module BpmSales
  module PanelHelper
  end
end

app/helpers/bpm_sales/report_helper.rb
module BpmSales
  module ReportHelper
  end
end

app/views/bpm_sales/invoices/_form.html.erb
<div>
  <%= f.label :bill_to %>
  <%= f.text_field :bill_to %>
</div>

<div>
  <%= f.label :due_at %>
  <%= f.date_select :due_at %>
</div>

app/views/bpm_sales/invoices/edit.html.erb
<h2>Edit Invoice</h2>

<%= form_for @invoice do |f| %>

    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Update Invoice" %> or <%= link_to "Cancel", :back %>
<% end %>

app/views/bpm_sales/invoices/index.html.erb
<h2>Invoices</h2>

<% if @invoices.empty? %>
  <em>There aren't any invoices.</em>
<% else %>
  <table class="table table-strip table-hover">
    <tr>
      <th>Id</th>
      <th>Company</th>
      <th>Created At</th>
      <th>Due On</th>
      <th>Paid On</th>
    </tr>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= link_to invoice.id, edit_invoice_url(invoice) %></td>
        <td><%= invoice['bill_to'] %></td>
        <td><%= invoice.created_at %></td>
        <td><%= invoice.due_at %></td>
        <td><%= invoice.paid_at %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= link_to "New Invoice", new_invoice_url %>

app/views/bpm_sales/invoices/new.html.erb
<h2>New Invoice</h2>

<%= form_for @invoice do |f| %>

    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Create Invoice" %>
<% end %>

app/views/bpm_sales/invoices/show.html.erb
<h2>Invoice #<%= @invoice.id %></h2>

<div>
  <strong>Company Name:</strong> <%= @invoice['bill_to'] %>
</div>

<div>
  <strong>Created At:</strong> <%= @invoice.created_at %>
</div>

<div>
  <strong>Due On:</strong> <%= @invoice.due_at %>
</div>

<div>
  <strong>Paid At:</strong>
  
  <% if @invoice.paid? %>
    <%= @invoice.paid_at %>
  <% else %>
     Unpaid (<%= link_to "Mark as Paid", mark_paid_invoice_url(@invoice), :method => :put %>)
  <% end %>
</div>

<h3>Total: <%= number_to_currency(@invoice.total) %></h3>

<h3><%= link_to "View PDF", invoice_url(@invoice, :format => :pdf) %></h3>

<div>
  <%= link_to "Edit Invoice Details", edit_invoice_url(@invoice) %>
</div>

<h2>Line Items</h2>

<table>
  <tr>
    <th>Description</th>
    <th>Quantity</th>
    <th>Unit Price</th>
    <th>Amount</th>
    <th></th>
  </tr>
  <% if @invoice.line_items.empty? %>
    <tr><td colspan="5"><em>There aren't any line items on this invoice.</em></td></tr>
  <% else %>
    <% @invoice.line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.description %></td>
        <td><%= line_item.quantity %></td>
        <td><%= number_to_currency(line_item.price) %></td>
        <td><%= number_to_currency(line_item.amount) %></td>
        <td><%= link_to "Edit", edit_invoice_line_item_url(@invoice, line_item) %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<div>
  <%= link_to "Add Line Item", new_invoice_line_item_url(@invoice) %>
</div>